# Generated by Django 4.1.2 on 2022-10-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('Author', models.CharField(max_length=50)),
                ('Isbn', models.EmailField(max_length=50)),
                ('Publisher', models.CharField(max_length=50)),
            ],
        ),
    ]
